name: 'subtree-splitter'
description: 'Sync your git repository subtree-splits'
inputs:
    config-path:
        required: true
        description: 'Configuration file path'
    batch-size:
        required: false
        description: 'How many subtreesplits should be processed in parallel'
        default: '4'
runs:
    using: 'node20'
    main: 'dist/index.js'
branding:
    icon: shuffle
    color: yellow
